### ISSUE TITLE
Allow writing results to file for CI tools

### ISSUE THREAD

**Issue by maurits-tellow** [hellotellow/node-structured#2]
Currently using this for CircleCI:

```yaml
task-lint-structure: &task-lint-structure
  run:
    name: Lint code base structure
    command: yarn structured | tee reports/structured.txt
```

Support for JSON/XML format would be great.
